# Generated by Django 6.0.7 on 2026-08-03 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('username_intentado', models.CharField(blank=True, max_length=150)),
                ('accion', models.CharField(choices=[('login_ok', 'Login exitoso'), ('login_fail', 'Login fallido'), ('run_manual', 'Ejecucion manual disparada')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PadronRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('disparado_por', models.CharField(choices=[('automatico', 'Automatico'), ('manual', 'Manual')], max_length=20)),
                ('estado', models.CharField(choices=[('en_progreso', 'En progreso'), ('ok', 'OK'), ('error', 'Error')], default='en_progreso', max_length=20)),
                ('total_consulta_gx', models.IntegerField(blank=True, null=True)),
                ('total_enviado_misrx', models.IntegerField(blank=True, null=True)),
                ('archivo_generado', models.CharField(blank=True, max_length=255)),
                ('misrx_padrones_registros_id', models.BigIntegerField(blank=True, null=True)),
                ('misrx_estado_descripcion', models.CharField(blank=True, max_length=255)),
                ('error_mensaje', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-iniciado_en'],
            },
        ),
        migrations.CreateModel(
            name='AfiliadoExcepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20)),
                ('nombre_completo', models.CharField(blank=True, max_length=255)),
                ('motivo', models.TextField()),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('tratado', 'Tratado')], default='pendiente', max_length=20)),
                ('run_deteccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excepciones_detectadas', to='padron.padronrun')),
            ],
            options={
                'ordering': ['-fecha_deteccion'],
                'constraints': [models.UniqueConstraint(fields=('dni', 'motivo'), name='unico_dni_motivo_excepcion')],
            },
        ),
    ]
