# Generated by Django 6.0.7 on 2026-08-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='padronrun',
            name='altas_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='padronrun',
            name='bajas_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='padronrun',
            name='dnis_incluidos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='padronrun',
            name='misrx_info',
            field=models.TextField(blank=True),
        ),
    ]
