# Generated by Django 6.0.7 on 2026-08-03 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0002_padronrun_altas_count_padronrun_bajas_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='padronrun',
            options={'ordering': ['-iniciado_en'], 'permissions': [('can_run_padron', 'Puede ejecutar la actualizacion del padron manualmente')]},
        ),
    ]
