# Generated by Django 5.2.15 on 2026-08-04 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0004_grupos_admin_operador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CronicoLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(choices=[('alta', 'Alta/Modificacion'), ('baja', 'Baja')], max_length=10)),
                ('dni', models.CharField(blank=True, max_length=20)),
                ('nro_afiliado', models.CharField(blank=True, max_length=20)),
                ('payload_enviado', models.JSONField(blank=True, null=True)),
                ('status_code_misrx', models.IntegerField(blank=True, null=True)),
                ('respuesta_misrx', models.TextField(blank=True)),
                ('exitoso', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'permissions': [('can_manage_cronicos', 'Puede cargar/dar de baja prescripciones cronicas en MisRx')],
            },
        ),
    ]
