# Generated by Django 5.2.15 on 2026-08-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0005_cronicolog'),
    ]

    operations = [
        migrations.CreateModel(
            name='VademecumItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.BigIntegerField(unique=True)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('presentacion', models.CharField(blank=True, max_length=255)),
                ('laboratorio', models.CharField(blank=True, max_length=255)),
                ('troquel', models.CharField(blank=True, max_length=50)),
                ('codigobarra', models.CharField(blank=True, max_length=50)),
                ('monodroga_id', models.BigIntegerField()),
                ('monodroga_nombre', models.CharField(max_length=255)),
                ('potencia', models.CharField(blank=True, max_length=100)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['monodroga_nombre'], name='padron_vade_monodro_9985d4_idx'), models.Index(fields=['nombre_producto'], name='padron_vade_nombre__2b2f0d_idx'), models.Index(fields=['monodroga_id'], name='padron_vade_monodro_54fa82_idx')],
            },
        ),
    ]
