# Generated by Django 5.2.15 on 2026-08-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0007_operador_permiso_cronicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronicolog',
            name='estado_anterior',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlogentry',
            name='accion',
            field=models.CharField(choices=[('login_ok', 'Login exitoso'), ('login_fail', 'Login fallido'), ('run_manual', 'Ejecucion manual disparada'), ('vademecum_upd', 'Vademecum actualizado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cronicolog',
            name='accion',
            field=models.CharField(choices=[('alta', 'Alta/Modificacion'), ('baja', 'Baja'), ('rollback', 'Rollback (admin)')], max_length=10),
        ),
    ]
