# Generated by Django 6.0.7 on 2026-08-04 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0008_cronicolog_estado_anterior_rollback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoConsultaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dni', models.CharField(blank=True, max_length=20)),
                ('total_recetas', models.IntegerField(blank=True, null=True)),
                ('exitoso', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'permissions': [('can_view_consumos', 'Puede consultar recetas y consumos por DNI en MisRx')],
            },
        ),
    ]
