# Generated by Django 5.2.15 on 2026-08-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0010_operador_permiso_consumos'),
    ]

    operations = [
        migrations.AddField(
            model_name='padronrun',
            name='altas_detalle',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='padronrun',
            name='bajas_detalle',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='padronrun',
            name='registros_incluidos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
